---
title: Aleksandar Todorović (r3bl)
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Hacker. Blogger. infosec enthusiast. Free culture and open source advocate.
  Ford-Mozilla Open Web fellow. Previously OCCRP tech associate.
url: https://r3bl.me
menu:
- title: Home
  url: https://r3bl.me
- title: Blog
  url: https://blog.r3bl.me/
- title: Projects
  url: https://r3bl.me/en/projects/
- title: Portfolio
  url: https://r3bl.me/en/portfolio/
- title: Contact
  url: https://r3bl.me/en/contact/
owner:
  name: Aleksandar Todorović
  site: https://r3bl.me
  avatar: images/avatar.jpg
  bio: Hacker. Blogger. infosec enthusiast. Free culture and open source advocate.
    Ford-Mozilla Open Web fellow. Previously OCCRP tech associate.
  email: aleksandar@r3bl.me
  twitter: r3bl_
  facebook: aleksandar.todorovic.r3bl
  github: aleksandar-todorovic
  google_plus: "+AleksandarTodorovićr3bl"
future: true
highlighter: rouge
markdown: kramdown
plugins:
- jekyll-redirect-from
- jekyll-sitemap
sass:
  sass_dir: common/_sass
  style: compressed
permalink: "/:categories/:title/"
include:
- ".htaccess"
exclude:
- lib
- config.rb
- Capfile
- config
- Gemfile
- Gemfile.lock
- README.md
- LICENSE
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules


layouts_dir:     common/_layouts
includes_dir:    common/_includes
