# Site settings

title: Aleksandar Todorović
email: aleksandar@r3bl.me

description: "Hacker. Blogger. infosec enthusiast. Free culture and open source advocate. Ford-Mozilla Open Web fellow. Previously OCCRP tech associate."
url: "https://r3bl.me" # the base hostname & protocol for your site

twitter_username:     r3bl_
github_username:      aleksandar-todorovic
facebook_username:    aleksandar.todorovic.r3bl

# Build settings
markdown: kramdown

permalink: /:categories/:title/

gems:
  - jekyll-sitemap
